<?php
//项目配置声明在这个文件中.
$CONFIG['debug']                        = 0;            // 项目的调试模式，1为打开，0为关闭
$CONFIG['route']['url_type']            = 2;            // url模式，1为字符串模式，2为pathinfo模式,3为rewrite模式
$CONFIG['route']['default_controller']  = 'index';      // 默认控制器文件
$CONFIG['route']['default_action']      = 'index';      // 默认action接口
$CONFIG['output']['charset'] 			= 'utf-8';	    // 页面字符集
$CONFIG['output']['errorlog'] 			= 0;	        // 是否记录错误日志
$CONFIG['output']['forceheader']		= 0;		    // 强制输出页面字符集，用于避免某些环境乱码,0为关闭，1为开启
$CONFIG['output']['gzip'] 				= 0;		    // 是否采用 Gzip 压缩输出
$CONFIG['output']['tmpl_cache'] 		= 1;		    // 是否开启模版缓存，0为内存输出做调试模式用，1为检测缓存输出做开发模式用，2为调用缓存输出，做正式环境用
$CONFIG['output']['layout_on'] 		    = 1;		    // 是否开启布局，0为关闭，1为开启
$CONFIG['output']['layout_name'] 		= 'layout';     // 布局的文件
$CONFIG['output']['layout_item'] 		= '{_content}'; // 布局的内部替换的标签名称
$CONFIG['output']['tmpl_suffix'] 		= '.php';		// 模版的后缀
$CONFIG['output']['default_tmpl'] 		= 'default';    // 默认模版目录
$CONFIG['output']['csszip'] 		    = 1;		    // 是否压缩css文件，1为压缩，0为不压缩
$CONFIG['output']['jszip'] 		        = 1;		    // 是否压缩js文件，0为不压缩，1为普通压缩，2为加密压缩
$CONFIG['output']['htmlzip'] 		    = 1;		    // 是否压缩html文件，0为不压缩，1为普通压缩
$CONFIG['loader']['libs']    		    = array();		// 是否加载外围的类
$CONFIG['loader']['helpers']     	    = array();		// 是否加载外围函数
$CONFIG['loader']['hooks']     		    = array();		// 是否加载钩子
$CONFIG['session']['prefix']            = 'pk_';        // session的前缀
$CONFIG['session']['id']                = 'phpk';       // session的id
$CONFIG['session']['expire']            = 1200;         // session的超时时间
$CONFIG['session']['auto_start']        = 1;            // 是否自启动session，1为开启，0为关闭
$CONFIG['cookie']['prefix']             = 'pk_';        // cookie的前缀
$CONFIG['cookie']['path']               = '/';          // cookie的有效路径
$CONFIG['cookie']['expire']             = 1200;         // cookie的超时时间
$CONFIG['cookie']['domain']             = '';           // cookie的作用域
$CONFIG['cache']['type']                = 'file';       // 缓存类型
$CONFIG['cache']['table']               = 'tb_cache';   // 缓存表的名称
$CONFIG['cache']['prefix']              = 'cache_';     // 缓存前缀
$CONFIG['cache']['time']                = 3600;         // 缓存过期时间
$CONFIG['cache']['check']               = true;         // 是否进行缓存的数据校验
$CONFIG['cache']['compress']            = true;         // 是否缓存压缩
$CONFIG['auth']['auth_on']              = 1;            //是否启动权限认证
$CONFIG['auth']['auth_type']            = 'phpk';       //权限认证方式
